name: sthlm-mesh

services:
  site:
    image: hugomods/hugo:exts-0.145.0 # Freeze hugo due to theme issue.
    command: server --buildDrafts --poll 500ms
    ports:
      - "1313:1313"
    volumes:
      - .:/src
